version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easydrop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easydrop-api
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      JWT_SECRET: your_very_secure_secret_key
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: easydrop
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db_data: